export const VARIANTS = [
  "primary",
  "primary-outline",
  "secondary",
  "secondary-outline",
  "success",
  "success-outline",
  "danger",
  "danger-outline",
  "warning",
  "warning-outline",
  "info",
  "light",
  "light-outline",
  "dark",
  "dark-grey",
  "gray",
  "tran-outline",
  "light-gray",
  "transparent",
  "light-blue",
  "light-blue-outline",
] as const;
